import type { POST_QUERY_RESULT } from "@/sanity/sanity.types";

/**
 * =========================================================
 * WRITING HEADING UTILITIES
 * =========================================================
 *
 * Shared utilities for article headings.
 *
 * These utilities are intentionally kept outside both the
 * article renderer and the Table of Contents component.
 *
 * This gives PostBody and TableOfContents one shared source
 * of truth for heading text and heading IDs.
 *
 * =========================================================
 */

type PostBodyValue = NonNullable<POST_QUERY_RESULT>["body"];

type PortableTextBlock = Extract<PostBodyValue[number], { _type: "block" }>;

/**
 * Converts heading text into a stable URL fragment.
 *
 * Example:
 *
 * "How I Built My Website"
 * → "how-i-built-my-website"
 *
 * Accented characters are normalized before generating
 * the fragment so that headings produce clean URLs.
 */
export function slugifyHeading(text: string): string {
  const slug = text
    .normalize("NFKD")
    .replace(/[\u0300-\u036f]/g, "")
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9\s-]/g, "")
    .replace(/\s+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");

  return slug || "section";
}

/**
 * Extracts the visible text from a Portable Text block.
 *
 * Portable Text stores the actual text inside span children.
 * We combine those spans to obtain the heading's readable
 * text before generating its URL fragment.
 */
export function getBlockText(block: PortableTextBlock): string {
  return block.children?.map((child) => child.text ?? "").join("") ?? "";
}

/**
 * Creates deterministic IDs for article headings.
 *
 * Duplicate headings receive a numeric suffix:
 *
 * "Performance"
 * → "performance"
 *
 * "Performance"
 * → "performance-2"
 *
 * "Performance"
 * → "performance-3"
 */
export function createHeadingIds(value: PostBodyValue): Map<string, string> {
  const ids = new Map<string, string>();
  const occurrences = new Map<string, number>();

  for (const block of value) {
    if (block._type !== "block" || !["h2", "h3", "h4"].includes(block.style ?? "")) {
      continue;
    }

    const text = getBlockText(block);
    const baseId = slugifyHeading(text);

    const occurrence = (occurrences.get(baseId) ?? 0) + 1;

    occurrences.set(baseId, occurrence);

    const id = occurrence === 1 ? baseId : `${baseId}-${occurrence}`;

    ids.set(block._key, id);
  }

  return ids;
}

/**
 * Extracts the headings required by the Table of Contents.
 *
 * The returned items use the same IDs generated by
 * createHeadingIds(), ensuring TOC links always match the
 * IDs rendered by PostBody.
 */
export function extractTableOfContents(
  value: PostBodyValue,
): Array<{
  id: string;
  text: string;
  level: 2 | 3 | 4;
}> {
  const headingIds = createHeadingIds(value);

  return value.flatMap((block) => {
    if (block._type !== "block") {
      return [];
    }

    if (
      block.style !== "h2" &&
      block.style !== "h3" &&
      block.style !== "h4"
    ) {
      return [];
    }

    const id = headingIds.get(block._key);

    if (!id) {
      return [];
    }

    const level =
      block.style === "h2"
        ? 2
        : block.style === "h3"
          ? 3
          : 4;

    return [
      {
        id,
        text: getBlockText(block),
        level,
      },
    ];
  });
}
