/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type Technology = {
  _id: string;
  _type: "technology";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  description?: string;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  badgeTheme:
    | "slate"
    | "stone"
    | "rose"
    | "red"
    | "orange"
    | "amber"
    | "yellow"
    | "lime"
    | "emerald"
    | "teal"
    | "cyan"
    | "sky"
    | "blue"
    | "indigo"
    | "violet"
    | "purple";
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top: number;
  bottom: number;
  left: number;
  right: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x: number;
  y: number;
  height: number;
  width: number;
};

export type Slug = {
  _type: "slug";
  current: string;
  source?: string;
};

export type TechnologyReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "technology";
};

export type Project = {
  _id: string;
  _type: "project";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  summary: string;
  metadata?: Metadata;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  gallery?: Array<{
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    caption?: string;
    _type: "image";
    _key: string;
  }>;
  demoVideo?: string;
  body: PortableText;
  technologies: Array<
    {
      _key: string;
    } & TechnologyReference
  >;
  status: "completed" | "in-progress" | "archived";
  featured?: boolean;
  completedAt?: string;
  liveDemo?: string;
  sourceCode?: string;
};

export type PortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href: string;
        openInNewTab?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt: string;
      caption?: string;
      _type: "image";
      _key: string;
    }
  | ({
      _key: string;
    } & Code)
  | ({
      _key: string;
    } & RichTableBlock)
  | ({
      _key: string;
    } & Callout)
>;

export type Metadata = {
  _type: "metadata";
  title?: string;
  description?: string;
  socialImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  socialImageAlt?: string;
  canonical?: string;
  noIndex?: boolean;
};

export type AuthorReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "author";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type TagReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "tag";
};

export type Post = {
  _id: string;
  _type: "post";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title: string;
  slug: Slug;
  excerpt: string;
  featuredImage: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body: PortableText;
  author: AuthorReference;
  category: CategoryReference;
  tags?: Array<
    {
      _key: string;
    } & TagReference
  >;
  technologies?: Array<
    {
      _key: string;
    } & TechnologyReference
  >;
  metadata?: Metadata;
  publishedAt: string;
};

export type Callout = {
  _type: "callout";
  type: "info" | "warning" | "note";
  title?: string;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href: string;
      openInNewTab?: boolean;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type TableCellContent = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href: string;
    openInNewTab?: boolean;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Tag = {
  _id: string;
  _type: "tag";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  badgeTheme:
    | "slate"
    | "stone"
    | "rose"
    | "red"
    | "orange"
    | "amber"
    | "yellow"
    | "lime"
    | "emerald"
    | "teal"
    | "cyan"
    | "sky"
    | "blue"
    | "indigo"
    | "violet"
    | "purple";
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  description?: string;
  badgeTheme:
    | "slate"
    | "stone"
    | "rose"
    | "red"
    | "orange"
    | "amber"
    | "yellow"
    | "lime"
    | "emerald"
    | "teal"
    | "cyan"
    | "sky"
    | "blue"
    | "indigo"
    | "violet"
    | "purple";
  metadata?: Metadata;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name: string;
  slug: Slug;
  avatar?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  bio?: PortableText;
  website?: string;
  github?: string;
  linkedin?: string;
  x?: string;
  expertise?: Array<string>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  siteName: string;
  tagline?: string;
  siteDescription: string;
  defaultSocialImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  contactEmail: string;
  github?: string;
  linkedin?: string;
  x?: string;
  youtube?: string;
  instagram?: string;
};

export type Content = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type RichTableBlock = RichTable;

export type ColumnHeader = {
  _type: "columnHeader";
  title?: string;
  cellIndex: number;
  width?: number;
};

export type RichTableCell = {
  _type: "richTableCell";
  content?: TableCellContent;
};

export type Row = {
  _type: "row";
  title?: string;
  cells?: Array<
    {
      _key: string;
    } & RichTableCell
  >;
};

export type RichTable = {
  _type: "richTable";
  rows: Array<
    {
      _key: string;
    } & Row
  >;
  columnHeaders?: Array<
    {
      _key: string;
    } & ColumnHeader
  >;
  hasColumnTitles?: boolean;
  hasRowTitles?: boolean;
  rowTitleWidth?: number;
};

export type Code = {
  _type: "code";
  language?: string;
  filename?: string;
  code?: string;
  highlightedLines?: Array<number>;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height: number;
  width: number;
  aspectRatio: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash: string;
  extension: string;
  mimeType: string;
  size: number;
  assetId: string;
  uploadId?: string;
  path: string;
  url: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityImageAssetReference
  | Technology
  | SanityImageCrop
  | SanityImageHotspot
  | Slug
  | TechnologyReference
  | Project
  | PortableText
  | Metadata
  | AuthorReference
  | CategoryReference
  | TagReference
  | Post
  | Callout
  | TableCellContent
  | Tag
  | Category
  | Author
  | SiteSettings
  | Content
  | RichTableBlock
  | ColumnHeader
  | RichTableCell
  | Row
  | RichTable
  | Code
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: src/sanity/lib/queries/posts.ts
// Variable: POSTS_QUERY
// Query: {    "posts": *[      _type == "post" &&      defined(title) &&      defined(slug.current) &&      defined(excerpt) &&      defined(featuredImage.asset) &&      defined(featuredImage.alt) &&      defined(author) &&      defined(category) &&      defined(publishedAt) &&      publishedAt <= now() &&      (        $category == "" ||        category->slug.current == $category      ) &&      (        $topic == "" ||        count(tags[@->slug.current == $topic]) > 0      ) &&      (        $q == "" ||        title match $q ||        excerpt match $q ||        category->name match $q ||        count(tags[@->name match $q]) > 0      )    ]    | order(publishedAt desc)    [$offset...$limit]    {      _id,      title,      "slug": slug.current,      excerpt,      publishedAt,     featuredImage {      "url": asset->url,      alt    },      category-> {        _id,        name,        "slug": slug.current,        badgeTheme      },      tags[]-> {        _id,        name,        "slug": slug.current,        badgeTheme      },      author-> {        _id,        name,        "slug": slug.current      }    },    "total": count(*[      _type == "post" &&      defined(title) &&      defined(slug.current) &&      defined(excerpt) &&      defined(featuredImage.asset) &&      defined(featuredImage.alt) &&      defined(author) &&      defined(category) &&      defined(publishedAt) &&      publishedAt <= now() &&      (        $category == "" ||        category->slug.current == $category      ) &&      (        $topic == "" ||        count(tags[@->slug.current == $topic]) > 0      ) &&      (        $q == "" ||        title match $q ||        excerpt match $q ||        category->name match $q ||        count(tags[@->name match $q]) > 0      )    ])  }
export type POSTS_QUERY_RESULT = {
  posts: Array<{
    _id: string;
    title: string;
    slug: string;
    excerpt: string;
    publishedAt: string;
    featuredImage: {
      url: string | null;
      alt: string;
    };
    category: {
      _id: string;
      name: string;
      slug: string;
      badgeTheme:
        | "amber"
        | "blue"
        | "cyan"
        | "emerald"
        | "indigo"
        | "lime"
        | "orange"
        | "purple"
        | "red"
        | "rose"
        | "sky"
        | "slate"
        | "stone"
        | "teal"
        | "violet"
        | "yellow";
    };
    tags: Array<{
      _id: string;
      name: string;
      slug: string;
      badgeTheme:
        | "amber"
        | "blue"
        | "cyan"
        | "emerald"
        | "indigo"
        | "lime"
        | "orange"
        | "purple"
        | "red"
        | "rose"
        | "sky"
        | "slate"
        | "stone"
        | "teal"
        | "violet"
        | "yellow";
    }> | null;
    author: {
      _id: string;
      name: string;
      slug: string;
    };
  }>;
  total: number;
};

// Source: src/sanity/lib/queries/posts.ts
// Variable: POST_QUERY
// Query: *[    _type == "post" &&    slug.current == $slug  ][0] {    _id,    _updatedAt,    title,    "slug": slug.current,    excerpt,    publishedAt,    featuredImage {      ...,      asset->    },    body[] {      ...,      _type == "image" => {        ...,        asset->      }    },    author-> {      _id,      name,      "slug": slug.current,      avatar {        ...,        asset->      },      bio,      website,      github,      linkedin,      x,      expertise    },    category-> {      _id,      name,      "slug": slug.current,      description,      badgeTheme    },    tags[]-> {      _id,      name,      "slug": slug.current,      badgeTheme    },    technologies[]-> {      _id,      title,      "slug": slug.current,      description,      logo {        ...,        asset->      },      badgeTheme    }  }
export type POST_QUERY_RESULT = {
  _id: string;
  _updatedAt: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  featuredImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "h4" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href: string;
          openInNewTab?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        _key: string;
        _type: "callout";
        type: "info" | "note" | "warning";
        title?: string;
        content: Array<{
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href: string;
            openInNewTab?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }>;
      }
    | {
        _key: string;
        _type: "code";
        language?: string;
        filename?: string;
        code?: string;
        highlightedLines?: Array<number>;
      }
    | {
        asset: {
          _id: string;
          _type: "sanity.imageAsset";
          _createdAt: string;
          _updatedAt: string;
          _rev: string;
          originalFilename?: string;
          label?: string;
          title?: string;
          description?: string;
          altText?: string;
          sha1hash: string;
          extension: string;
          mimeType: string;
          size: number;
          assetId: string;
          uploadId?: string;
          path: string;
          url: string;
          metadata?: SanityImageMetadata;
          source?: SanityAssetSourceData;
        } | null;
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        alt: string;
        caption?: string;
        _type: "image";
        _key: string;
      }
    | {
        _key: string;
        _type: "richTable";
        rows: Array<
          {
            _key: string;
          } & Row
        >;
        columnHeaders?: Array<
          {
            _key: string;
          } & ColumnHeader
        >;
        hasColumnTitles?: boolean;
        hasRowTitles?: boolean;
        rowTitleWidth?: number;
      }
  >;
  author: {
    _id: string;
    name: string;
    slug: string;
    avatar: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    bio: PortableText | null;
    website: string | null;
    github: string | null;
    linkedin: string | null;
    x: string | null;
    expertise: Array<string> | null;
  };
  category: {
    _id: string;
    name: string;
    slug: string;
    description: string | null;
    badgeTheme:
      | "amber"
      | "blue"
      | "cyan"
      | "emerald"
      | "indigo"
      | "lime"
      | "orange"
      | "purple"
      | "red"
      | "rose"
      | "sky"
      | "slate"
      | "stone"
      | "teal"
      | "violet"
      | "yellow";
  };
  tags: Array<{
    _id: string;
    name: string;
    slug: string;
    badgeTheme:
      | "amber"
      | "blue"
      | "cyan"
      | "emerald"
      | "indigo"
      | "lime"
      | "orange"
      | "purple"
      | "red"
      | "rose"
      | "sky"
      | "slate"
      | "stone"
      | "teal"
      | "violet"
      | "yellow";
  }> | null;
  technologies: Array<{
    _id: string;
    title: string;
    slug: string;
    description: string | null;
    logo: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    badgeTheme:
      | "amber"
      | "blue"
      | "cyan"
      | "emerald"
      | "indigo"
      | "lime"
      | "orange"
      | "purple"
      | "red"
      | "rose"
      | "sky"
      | "slate"
      | "stone"
      | "teal"
      | "violet"
      | "yellow";
  }> | null;
} | null;

// Source: src/sanity/lib/queries/posts.ts
// Variable: POST_METADATA_QUERY
// Query: *[    _type == "post" &&    slug.current == $slug  ][0] {    title,    "slug": slug.current,    excerpt,    publishedAt,    _updatedAt,    featuredImage {      ...,      asset->    },    metadata {      title,      description,      socialImage {        ...,        asset->      },      socialImageAlt,      canonical,      noIndex    },    author-> {      name    }  }
export type POST_METADATA_QUERY_RESULT = {
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  _updatedAt: string;
  featuredImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt: string;
    _type: "image";
  };
  metadata: {
    title: string | null;
    description: string | null;
    socialImage: {
      asset: {
        _id: string;
        _type: "sanity.imageAsset";
        _createdAt: string;
        _updatedAt: string;
        _rev: string;
        originalFilename?: string;
        label?: string;
        title?: string;
        description?: string;
        altText?: string;
        sha1hash: string;
        extension: string;
        mimeType: string;
        size: number;
        assetId: string;
        uploadId?: string;
        path: string;
        url: string;
        metadata?: SanityImageMetadata;
        source?: SanityAssetSourceData;
      } | null;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    socialImageAlt: string | null;
    canonical: string | null;
    noIndex: boolean | null;
  } | null;
  author: {
    name: string;
  };
} | null;

// Source: src/sanity/lib/queries/posts.ts
// Variable: POST_SLUGS_QUERY
// Query: *[    _type == "post" &&    defined(slug.current)  ] {    "slug": slug.current  }
export type POST_SLUGS_QUERY_RESULT = Array<{
  slug: string;
}>;

// Source: src/sanity/lib/queries/posts.ts
// Variable: WRITING_FILTERS_QUERY
// Query: {    "categories": *[      _type == "category" &&      defined(name) &&      defined(slug.current)    ] | order(name asc) {      _id,      name,      "slug": slug.current,      badgeTheme    },    "topics": *[      _type == "tag" &&      defined(name) &&      defined(slug.current)    ] | order(name asc) {      _id,      name,      "slug": slug.current,      badgeTheme    }  }
export type WRITING_FILTERS_QUERY_RESULT = {
  categories: Array<{
    _id: string;
    name: string;
    slug: string;
    badgeTheme:
      | "amber"
      | "blue"
      | "cyan"
      | "emerald"
      | "indigo"
      | "lime"
      | "orange"
      | "purple"
      | "red"
      | "rose"
      | "sky"
      | "slate"
      | "stone"
      | "teal"
      | "violet"
      | "yellow";
  }>;
  topics: Array<{
    _id: string;
    name: string;
    slug: string;
    badgeTheme:
      | "amber"
      | "blue"
      | "cyan"
      | "emerald"
      | "indigo"
      | "lime"
      | "orange"
      | "purple"
      | "red"
      | "rose"
      | "sky"
      | "slate"
      | "stone"
      | "teal"
      | "violet"
      | "yellow";
  }>;
};

// Source: src/sanity/lib/queries/posts.ts
// Variable: LATEST_POSTS_QUERY
// Query: *[    _type == "post" &&    defined(title) &&    defined(slug.current) &&    defined(excerpt) &&    defined(featuredImage.asset) &&    defined(featuredImage.alt) &&    defined(author) &&    defined(category) &&    defined(publishedAt) &&    publishedAt <= now()  ]  | order(publishedAt desc)  [0...$limit]  {    _id,    title,    "slug": slug.current,    excerpt,    publishedAt,    featuredImage {      "url": asset->url,      "alt": alt},    category-> {      _id,      name,      "slug": slug.current,      badgeTheme    },    tags[]-> {      _id,      name,      "slug": slug.current,      badgeTheme    },    author-> {      _id,      name,      "slug": slug.current    }  }
export type LATEST_POSTS_QUERY_RESULT = Array<{
  _id: string;
  title: string;
  slug: string;
  excerpt: string;
  publishedAt: string;
  featuredImage: {
    url: string | null;
    alt: string;
  };
  category: {
    _id: string;
    name: string;
    slug: string;
    badgeTheme:
      | "amber"
      | "blue"
      | "cyan"
      | "emerald"
      | "indigo"
      | "lime"
      | "orange"
      | "purple"
      | "red"
      | "rose"
      | "sky"
      | "slate"
      | "stone"
      | "teal"
      | "violet"
      | "yellow";
  };
  tags: Array<{
    _id: string;
    name: string;
    slug: string;
    badgeTheme:
      | "amber"
      | "blue"
      | "cyan"
      | "emerald"
      | "indigo"
      | "lime"
      | "orange"
      | "purple"
      | "red"
      | "rose"
      | "sky"
      | "slate"
      | "stone"
      | "teal"
      | "violet"
      | "yellow";
  }> | null;
  author: {
    _id: string;
    name: string;
    slug: string;
  };
}>;

// Source: src/sanity/lib/queries/siteSettings.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0] {    _id,    siteName,    tagline,    siteDescription,    defaultSocialImage {      ...,      asset->,      crop,      hotspot    },    contactEmail,    github,    linkedin,    x,    youtube,    instagram  }
export type SITE_SETTINGS_QUERY_RESULT = {
  _id: string;
  siteName: string;
  tagline: string | null;
  siteDescription: string;
  defaultSocialImage: {
    asset: {
      _id: string;
      _type: "sanity.imageAsset";
      _createdAt: string;
      _updatedAt: string;
      _rev: string;
      originalFilename?: string;
      label?: string;
      title?: string;
      description?: string;
      altText?: string;
      sha1hash: string;
      extension: string;
      mimeType: string;
      size: number;
      assetId: string;
      uploadId?: string;
      path: string;
      url: string;
      metadata?: SanityImageMetadata;
      source?: SanityAssetSourceData;
    } | null;
    media?: unknown;
    hotspot: SanityImageHotspot | null;
    crop: SanityImageCrop | null;
    _type: "image";
  } | null;
  contactEmail: string;
  github: string | null;
  linkedin: string | null;
  x: string | null;
  youtube: string | null;
  instagram: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n  {\n    "posts": *[\n      _type == "post" &&\n      defined(title) &&\n      defined(slug.current) &&\n      defined(excerpt) &&\n      defined(featuredImage.asset) &&\n      defined(featuredImage.alt) &&\n      defined(author) &&\n      defined(category) &&\n      defined(publishedAt) &&\n      publishedAt <= now() &&\n\n      (\n        $category == "" ||\n        category->slug.current == $category\n      ) &&\n\n      (\n        $topic == "" ||\n        count(tags[@->slug.current == $topic]) > 0\n      ) &&\n\n      (\n        $q == "" ||\n        title match $q ||\n        excerpt match $q ||\n        category->name match $q ||\n        count(tags[@->name match $q]) > 0\n      )\n    ]\n    | order(publishedAt desc)\n    [$offset...$limit]\n    {\n      _id,\n      title,\n      "slug": slug.current,\n      excerpt,\n      publishedAt,\n\n     featuredImage {\n      "url": asset->url,\n      alt\n    },\n\n      category-> {\n        _id,\n        name,\n        "slug": slug.current,\n        badgeTheme\n      },\n\n      tags[]-> {\n        _id,\n        name,\n        "slug": slug.current,\n        badgeTheme\n      },\n\n      author-> {\n        _id,\n        name,\n        "slug": slug.current\n      }\n    },\n\n    "total": count(*[\n      _type == "post" &&\n      defined(title) &&\n      defined(slug.current) &&\n      defined(excerpt) &&\n      defined(featuredImage.asset) &&\n      defined(featuredImage.alt) &&\n      defined(author) &&\n      defined(category) &&\n      defined(publishedAt) &&\n      publishedAt <= now() &&\n\n      (\n        $category == "" ||\n        category->slug.current == $category\n      ) &&\n\n      (\n        $topic == "" ||\n        count(tags[@->slug.current == $topic]) > 0\n      ) &&\n\n      (\n        $q == "" ||\n        title match $q ||\n        excerpt match $q ||\n        category->name match $q ||\n        count(tags[@->name match $q]) > 0\n      )\n    ])\n  }\n': POSTS_QUERY_RESULT;
    '\n  *[\n    _type == "post" &&\n    slug.current == $slug\n  ][0] {\n    _id,\n    _updatedAt,\n\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n\n    featuredImage {\n      ...,\n      asset->\n    },\n\n    body[] {\n      ...,\n\n      _type == "image" => {\n        ...,\n        asset->\n      }\n    },\n\n    author-> {\n      _id,\n      name,\n      "slug": slug.current,\n      avatar {\n        ...,\n        asset->\n      },\n      bio,\n      website,\n      github,\n      linkedin,\n      x,\n      expertise\n    },\n\n    category-> {\n      _id,\n      name,\n      "slug": slug.current,\n      description,\n      badgeTheme\n    },\n\n    tags[]-> {\n      _id,\n      name,\n      "slug": slug.current,\n      badgeTheme\n    },\n\n    technologies[]-> {\n      _id,\n      title,\n      "slug": slug.current,\n      description,\n      logo {\n        ...,\n        asset->\n      },\n      badgeTheme\n    }\n  }\n': POST_QUERY_RESULT;
    '\n  *[\n    _type == "post" &&\n    slug.current == $slug\n  ][0] {\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n    _updatedAt,\n\n    featuredImage {\n      ...,\n      asset->\n    },\n\n    metadata {\n      title,\n      description,\n\n      socialImage {\n        ...,\n        asset->\n      },\n\n      socialImageAlt,\n      canonical,\n      noIndex\n    },\n\n    author-> {\n      name\n    }\n  }\n': POST_METADATA_QUERY_RESULT;
    '\n  *[\n    _type == "post" &&\n    defined(slug.current)\n  ] {\n    "slug": slug.current\n  }\n': POST_SLUGS_QUERY_RESULT;
    '\n  {\n    "categories": *[\n      _type == "category" &&\n      defined(name) &&\n      defined(slug.current)\n    ] | order(name asc) {\n      _id,\n      name,\n      "slug": slug.current,\n      badgeTheme\n    },\n\n    "topics": *[\n      _type == "tag" &&\n      defined(name) &&\n      defined(slug.current)\n    ] | order(name asc) {\n      _id,\n      name,\n      "slug": slug.current,\n      badgeTheme\n    }\n  }\n': WRITING_FILTERS_QUERY_RESULT;
    '\n  *[\n    _type == "post" &&\n    defined(title) &&\n    defined(slug.current) &&\n    defined(excerpt) &&\n    defined(featuredImage.asset) &&\n    defined(featuredImage.alt) &&\n    defined(author) &&\n    defined(category) &&\n    defined(publishedAt) &&\n    publishedAt <= now()\n  ]\n  | order(publishedAt desc)\n  [0...$limit]\n  {\n    _id,\n    title,\n    "slug": slug.current,\n    excerpt,\n    publishedAt,\n\n    featuredImage {\n      "url": asset->url,\n      "alt": alt\n},\n\n    category-> {\n      _id,\n      name,\n      "slug": slug.current,\n      badgeTheme\n    },\n\n    tags[]-> {\n      _id,\n      name,\n      "slug": slug.current,\n      badgeTheme\n    },\n\n    author-> {\n      _id,\n      name,\n      "slug": slug.current\n    }\n  }\n': LATEST_POSTS_QUERY_RESULT;
    '\n  *[_type == "siteSettings"][0] {\n    _id,\n\n    siteName,\n    tagline,\n    siteDescription,\n\n    defaultSocialImage {\n      ...,\n      asset->,\n      crop,\n      hotspot\n    },\n\n    contactEmail,\n\n    github,\n    linkedin,\n    x,\n    youtube,\n    instagram\n  }\n': SITE_SETTINGS_QUERY_RESULT;
  }
}
